### PR TITLE
Andrew's Comments

### PR DESCRIPTION
**Pull request by andrew-hossack**
Hey John, will be reviewing your code over the next day or two. Hope I can make some helpful suggestions!

### CODE REVIEW

**Comment by andrew-hossack** [comment]
In App.py
https://github.com/mirackara/projectscatter/blob/andrew-dev/app.py#L3 

Two things here, sendShowData is not used. Generally you want to clean up unused imports. Additionally, wildcard imports "from foo import *" are not good. They add unnecessary modules to the python runtime.

**Comment by andrew-hossack** [comment]
App.py https://github.com/mirackara/projectscatter/blob/andrew-dev/app.py#L11 

You'll want to start commenting your code more. Check out this as inspiration https://realpython.com/python-comments-guide/

**Comment by andrew-hossack** [comment]
App.py https://github.com/mirackara/projectscatter/blob/andrew-dev/app.py#L25 https://github.com/mirackara/projectscatter/blob/andrew-dev/app.py#L84

Avoid bare except clauses at all costs! From Google's style guide https://google.github.io/styleguide/pyguide.html: 

> Never use catch-all except: statements, or catch Exception or StandardError, unless you are

> re-raising the exception, or
creating an isolation point in the program where exceptions are not propagated but are recorded and suppressed instead, such as protecting a thread from crashing by guarding its outermost block.

**Comment by andrew-hossack** [comment]
App.py https://github.com/mirackara/projectscatter/blob/andrew-dev/app.py#L22

Bit of a nit-pick here, but try to avoid "magic-numbers" like this. If you include them, maybe include them as class-level or #define them globally in the module. You could also add a comment here explaining what 200 is.

**Comment by andrew-hossack** [comment]
App.py https://github.com/mirackara/projectscatter/blob/andrew-dev/app.py#L32

You can do a raw format string here, eg. r'Schitt's Creek' and you will not need the escape char.

**Comment by andrew-hossack** [comment]
GenerateShowData https://github.com/mirackara/projectscatter/blob/andrew-dev/GenerateShowData.py#L3

Unused import itertools

**Comment by andrew-hossack** [comment]
GenerateShowData https://github.com/mirackara/projectscatter/blob/andrew-dev/GenerateShowData.py#L18

showNames dictionary not used

https://github.com/mirackara/projectscatter/blob/andrew-dev/GenerateShowData.py#L25

Var counter not used

https://github.com/mirackara/projectscatter/blob/andrew-dev/GenerateShowData.py#L29

Again can use raw format string

https://github.com/mirackara/projectscatter/blob/andrew-dev/GenerateShowData.py#L15

rawShowNames file resource never explicitly closed after creation

**Comment by andrew-hossack** [comment]
General critique here, you'll want to start commenting more on your code here. In some instances, it is a bit difficult to follow what is going on.

**Review by mirackara — APPROVED** [review]
PEP8 Formatting looks great. Will work on other issues in pull request tonight.

**Comment by mirackara** [comment]
> 
> 
> In App.py
> https://github.com/mirackara/projectscatter/blob/andrew-dev/app.py#L3
> 
> Two things here, sendShowData is not used. Generally you want to clean up unused imports. Additionally, wildcard imports "from foo import *" are not good. They add unnecessary modules to the python runtime.

It's used here 

https://github.com/mirackara/projectscatter/blob/ec381b8a9531e058e7d5e5902dceabf90c9d4a34/app.py#L20

I have fixed the import to properly import the `getShowData()` function

**Comment by mirackara** [comment]
> 
> 
> App.py https://github.com/mirackara/projectscatter/blob/andrew-dev/app.py#L22
> 
> Bit of a nit-pick here, but try to avoid "magic-numbers" like this. If you include them, maybe include them as class-level or #define them globally in the module. You could also add a comment here explaining what 200 is.

I agree. Changed status codes to easier to read codes.

**Comment by mirackara** [comment]
> 
> 
> GenerateShowData https://github.com/mirackara/projectscatter/blob/andrew-dev/GenerateShowData.py#L3
> 
> Unused import itertools

Fixed!

**Pull request merged**
